//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signee.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Signee.Resources.Resources.Resource.cs", typeof(Resource_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatele se nepodařilo vytvořit..
        /// </summary>
        public static string Auth_CantCreateUser {
            get {
                return ResourceManager.GetString("Auth_CantCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné přihlašovací údaje..
        /// </summary>
        public static string Auth_InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení úspěšné..
        /// </summary>
        public static string Auth_LoginSuccessfull {
            get {
                return ResourceManager.GetString("Auth_LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel neexistuje.
        ///.
        /// </summary>
        public static string Auth_NoExistentUser {
            get {
                return ResourceManager.GetString("Auth_NoExistentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při načítání displeje s ID: {id} se vyskytla chyba..
        /// </summary>
        public static string ManagerWeb_DisplayIdRetreivalError {
            get {
                return ResourceManager.GetString("ManagerWeb_DisplayIdRetreivalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při načítání displejů se vyskytla chyba..
        /// </summary>
        public static string ManagerWeb_DisplaysRetreivalError {
            get {
                return ResourceManager.GetString("ManagerWeb_DisplaysRetreivalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při vytváření nového displeje nastala chyba..
        /// </summary>
        public static string ManagerWeb_ErrorCreatingDisplay {
            get {
                return ResourceManager.GetString("ManagerWeb_ErrorCreatingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při vytváření výchozího admin účtu se vyskytla chyba.
        /// </summary>
        public static string PopulateDb_AdminUserCreationError {
            get {
                return ResourceManager.GetString("PopulateDb_AdminUserCreationError", resourceCulture);
            }
        }
    }
}
